"""initial schema

The whole schema of IMPLEMENTATION.md §6, in one revision. This is the only
migration; keep the history linear and check `alembic heads` after every new
one. v1.0 branched here -- two migrations claiming the same parent -- and
untangling it cost more than the rewrite did.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-23 13:40:56.074648
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# §5: the native enum types, created explicitly and before any table that
# references them. The models declare `create_type=False` precisely so that
# this block is the single place they come into existence.
ENUM_TYPES: dict[str, tuple[str, ...]] = {
    "channel": ("telegram", "email", "web", "whatsapp"),
    "modality": ("online", "onsite"),
    "request_status": (
        "pending",
        "negotiating",
        "confirmed",
        "rejected",
        "expired",
        "cancelled",
        "completed",
    ),
    "slot_status": ("available", "held", "booked", "blocked"),
    "negotiation_kind": ("proposal", "counter", "accept", "decline", "note"),
    "sender_type": ("admin", "client", "system"),
    "waitlist_status": ("new", "contacted", "converted", "closed"),
    "booking_mode": ("slots", "negotiation"),
    "token_purpose": ("login", "link_channel", "view_request"),
    "outbox_status": ("pending", "sending", "sent", "failed", "dead"),
    "reminder_state": ("scheduled", "sent", "skipped", "cancelled"),
    "actor_type": ("admin", "client", "system"),
    "content_block_kind": ("text", "link_button"),
}


def upgrade() -> None:
    for type_name, values in ENUM_TYPES.items():
        rendered = ", ".join(f"'{value}'" for value in values)
        op.execute(f"CREATE TYPE {type_name} AS ENUM ({rendered})")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('default_language', sa.Text(), server_default='ru', nullable=False),
    sa.Column('timezone', sa.Text(), server_default='Asia/Yerevan', nullable=False),
    sa.Column('clinic_onsite_url', sa.Text(), nullable=True),
    sa.Column('online_meeting_url', sa.Text(), nullable=True),
    sa.Column('availability_on', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('booking_mode', postgresql.ENUM('slots', 'negotiation', name='booking_mode', create_type=False), server_default='slots', nullable=False),
    sa.Column('fallback_to_negotiation', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('negotiation_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('auto_confirm_slots', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('slot_hold_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('pending_expiry_hours', sa.Integer(), server_default='48', nullable=False),
    sa.Column('cancel_window_hours', sa.Integer(), server_default='24', nullable=False),
    sa.Column('reminder_offsets_min', sa.ARRAY(sa.Integer()), server_default='{1440,60}', nullable=False),
    sa.Column('retention_months', sa.Integer(), server_default='12', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice'))
    )
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_admin_user_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_user')),
    sa.UniqueConstraint('practice_id', 'username', name=op.f('uq_admin_user_practice_id_username'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('actor_type', postgresql.ENUM('admin', 'client', 'system', name='actor_type', create_type=False), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_audit_log_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('client',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('erased_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_client_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client'))
    )
    op.create_table('content_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('show_in_menu', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_content_topic_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_topic')),
    sa.UniqueConstraint('practice_id', 'code', name=op.f('uq_content_topic_practice_id_code'))
    )
    op.create_table('session_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('duration_min', sa.Integer(), server_default='60', nullable=False),
    sa.Column('price_amount_minor', sa.Integer(), nullable=True),
    sa.Column('price_currency', sa.Text(), nullable=True),
    sa.Column('price_display_override', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_session_type_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_type')),
    sa.UniqueConstraint('practice_id', 'code', name=op.f('uq_session_type_practice_id_code'))
    )
    op.create_table('slot',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), server_default='60', nullable=False),
    sa.Column('modality', postgresql.ENUM('online', 'onsite', name='modality', create_type=False), nullable=True),
    sa.Column('status', postgresql.ENUM('available', 'held', 'booked', 'blocked', name='slot_status', create_type=False), server_default='available', nullable=False),
    sa.Column('hold_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('held_by_request', sa.BigInteger(), nullable=True),
    sa.Column('booked_request', sa.BigInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'booked') = (booked_request IS NOT NULL)", name=op.f('ck_slot_booked_implies_booked_request')),
    sa.CheckConstraint("(status = 'held') = (hold_expires_at IS NOT NULL AND held_by_request IS NOT NULL)", name=op.f('ck_slot_held_implies_hold_fields')),
    sa.CheckConstraint("status NOT IN ('available', 'blocked') OR (hold_expires_at IS NULL AND held_by_request IS NULL AND booked_request IS NULL)", name=op.f('ck_slot_free_implies_no_reservation')),
    # The two foreign keys to booking_request are deliberately absent here:
    # slot and booking_request reference each other, so they are added by
    # ALTER TABLE at the end of this migration (§6.5).
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_slot_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slot'))
    )
    op.create_index('ix_slot_practice_id_status_starts_at', 'slot', ['practice_id', 'status', 'starts_at'], unique=False)
    op.create_index('slot_unique_offer', 'slot', ['practice_id', 'starts_at', 'modality'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('timezone_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('iana_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_timezone_option_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timezone_option')),
    sa.UniqueConstraint('practice_id', 'iana_name', name=op.f('uq_timezone_option_practice_id_iana_name'))
    )
    op.create_table('translation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_translation_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translation')),
    sa.UniqueConstraint('practice_id', 'lang', 'key', name=op.f('uq_translation_practice_id_lang_key'))
    )
    op.create_table('admin_session',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_user.id'], name=op.f('fk_admin_session_admin_user_id_admin_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_admin_session_token_hash'))
    )
    op.create_table('auth_token',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('purpose', postgresql.ENUM('login', 'link_channel', 'view_request', name='token_purpose', create_type=False), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_auth_token_client_id_client'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_auth_token_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_token_token_hash'))
    )
    op.create_table('booking_request',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('session_type_id', sa.Integer(), nullable=False),
    sa.Column('modality', postgresql.ENUM('online', 'onsite', name='modality', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'negotiating', 'confirmed', 'rejected', 'expired', 'cancelled', 'completed', name='request_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('source_channel', postgresql.ENUM('telegram', 'email', 'web', 'whatsapp', name='channel', create_type=False), nullable=False),
    sa.Column('slot_id', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scheduled_duration_min', sa.Integer(), nullable=True),
    sa.Column('client_timezone', sa.Text(), nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('desired_time_text', sa.Text(), nullable=True),
    sa.Column('problem_text', sa.Text(), nullable=True),
    sa.Column('contact_note', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancelled_by', postgresql.ENUM('admin', 'client', 'system', name='actor_type', create_type=False), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'confirmed' OR (scheduled_start IS NOT NULL AND confirmed_at IS NOT NULL)", name=op.f('ck_booking_request_confirmed_requires_schedule')),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_booking_request_client_id_client')),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_booking_request_practice_id_practice')),
    sa.ForeignKeyConstraint(['session_type_id'], ['session_type.id'], name=op.f('fk_booking_request_session_type_id_session_type')),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], name=op.f('fk_booking_request_slot_id_slot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_request')),
    sa.UniqueConstraint('uuid', name=op.f('uq_booking_request_uuid'))
    )
    op.create_index('ix_booking_request_client_id', 'booking_request', ['client_id'], unique=False)
    op.create_index('ix_booking_request_practice_id_status_created_at', 'booking_request', ['practice_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_booking_request_scheduled_start', 'booking_request', ['scheduled_start'], unique=False, postgresql_where=sa.text("status = 'confirmed'"))
    op.create_table('content_block',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', postgresql.ENUM('text', 'link_button', name='content_block_kind', create_type=False), server_default='text', nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_content_block_practice_id_practice')),
    sa.ForeignKeyConstraint(['topic_id'], ['content_topic.id'], name=op.f('fk_content_block_topic_id_content_topic'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_block')),
    sa.UniqueConstraint('topic_id', 'lang', 'position', name=op.f('uq_content_block_topic_id_lang_position'))
    )
    op.create_table('identity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('channel', postgresql.ENUM('telegram', 'email', 'web', 'whatsapp', name='channel', create_type=False), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_identity_client_id_client'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_identity_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity')),
    sa.UniqueConstraint('practice_id', 'channel', 'external_id', name=op.f('uq_identity_practice_id_channel_external_id'))
    )
    op.create_index('ix_identity_client_id', 'identity', ['client_id'], unique=False)
    op.create_table('slot_session_type',
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('session_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_type_id'], ['session_type.id'], name=op.f('fk_slot_session_type_session_type_id_session_type'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], name=op.f('fk_slot_session_type_slot_id_slot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', 'session_type_id', name=op.f('pk_slot_session_type'))
    )
    op.create_table('waitlist_entry',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('problem_text', sa.Text(), nullable=True),
    sa.Column('contact_note', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('new', 'contacted', 'converted', 'closed', name='waitlist_status', create_type=False), server_default='new', nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('contacted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_waitlist_entry_client_id_client')),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_waitlist_entry_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waitlist_entry')),
    sa.UniqueConstraint('uuid', name=op.f('uq_waitlist_entry_uuid'))
    )
    op.create_table('content_block_revision',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('block_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['content_block.id'], name=op.f('fk_content_block_revision_block_id_content_block'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_block_revision')),
    sa.UniqueConstraint('block_id', 'version', name=op.f('uq_content_block_revision_block_id_version'))
    )
    op.create_table('negotiation_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('sender', postgresql.ENUM('admin', 'client', 'system', name='sender_type', create_type=False), nullable=False),
    sa.Column('kind', postgresql.ENUM('proposal', 'counter', 'accept', 'decline', 'note', name='negotiation_kind', create_type=False), nullable=False),
    sa.Column('proposed_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['booking_request.id'], name=op.f('fk_negotiation_message_request_id_booking_request'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_negotiation_message'))
    )
    op.create_index('ix_negotiation_message_request_id_created_at', 'negotiation_message', ['request_id', 'created_at'], unique=False)
    op.create_table('outbox_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('channel', postgresql.ENUM('telegram', 'email', 'web', 'whatsapp', name='channel', create_type=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('intent_key', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'sending', 'sent', 'failed', 'dead', name='outbox_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_user.id'], name=op.f('fk_outbox_message_admin_user_id_admin_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_outbox_message_client_id_client'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_outbox_message_practice_id_practice')),
    sa.ForeignKeyConstraint(['request_id'], ['booking_request.id'], name=op.f('fk_outbox_message_request_id_booking_request'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_message')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_outbox_message_dedupe_key'))
    )
    op.create_index('ix_outbox_message_status_next_attempt_at', 'outbox_message', ['status', 'next_attempt_at'], unique=False)
    op.create_table('reminder',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('offset_min', sa.Integer(), nullable=False),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('state', postgresql.ENUM('scheduled', 'sent', 'skipped', 'cancelled', name='reminder_state', create_type=False), server_default='scheduled', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fired_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['booking_request.id'], name=op.f('fk_reminder_request_id_booking_request'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder')),
    sa.UniqueConstraint('request_id', 'offset_min', name=op.f('uq_reminder_request_id_offset_min'))
    )
    op.create_index('ix_reminder_state_due_at', 'reminder', ['state', 'due_at'], unique=False)
    op.create_table('outbox_attempt',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('attempted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['outbox_message.id'], name=op.f('fk_outbox_attempt_message_id_outbox_message'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_attempt'))
    )
    # ### end Alembic commands ###

    # §6.5: the deferred slot -> booking_request foreign keys, now that both
    # tables exist. ON DELETE SET NULL, so deleting a request never deletes the
    # slot it was holding.
    op.create_foreign_key(
        "fk_slot_held_by_request_booking_request",
        "slot",
        "booking_request",
        ["held_by_request"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_slot_booked_request_booking_request",
        "slot",
        "booking_request",
        ["booked_request"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    # Drop the circular foreign keys first, or the table drops below deadlock
    # on each other.
    op.drop_constraint("fk_slot_booked_request_booking_request", "slot", type_="foreignkey")
    op.drop_constraint("fk_slot_held_by_request_booking_request", "slot", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox_attempt')
    op.drop_index('ix_reminder_state_due_at', table_name='reminder')
    op.drop_table('reminder')
    op.drop_index('ix_outbox_message_status_next_attempt_at', table_name='outbox_message')
    op.drop_table('outbox_message')
    op.drop_index('ix_negotiation_message_request_id_created_at', table_name='negotiation_message')
    op.drop_table('negotiation_message')
    op.drop_table('content_block_revision')
    op.drop_table('waitlist_entry')
    op.drop_table('slot_session_type')
    op.drop_index('ix_identity_client_id', table_name='identity')
    op.drop_table('identity')
    op.drop_table('content_block')
    op.drop_index('ix_booking_request_scheduled_start', table_name='booking_request', postgresql_where=sa.text("status = 'confirmed'"))
    op.drop_index('ix_booking_request_practice_id_status_created_at', table_name='booking_request')
    op.drop_index('ix_booking_request_client_id', table_name='booking_request')
    op.drop_table('booking_request')
    op.drop_table('auth_token')
    op.drop_table('admin_session')
    op.drop_table('translation')
    op.drop_table('timezone_option')
    op.drop_index('slot_unique_offer', table_name='slot', postgresql_nulls_not_distinct=True)
    op.drop_index('ix_slot_practice_id_status_starts_at', table_name='slot')
    op.drop_table('slot')
    op.drop_table('session_type')
    op.drop_table('content_topic')
    op.drop_table('client')
    op.drop_table('audit_log')
    op.drop_table('admin_user')
    op.drop_table('practice')
    # ### end Alembic commands ###

    # The enum types outlive the tables that used them; drop them last.
    for type_name in reversed(list(ENUM_TYPES)):
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
