"""flow state

Revision ID: 0002_flow_state
Revises: 0001_initial_schema
Create Date: 2026-08-23 18:26:26.472426
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0002_flow_state"
down_revision: str | None = "0001_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_state',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('channel', postgresql.ENUM('telegram', 'email', 'web', 'whatsapp', name='channel', create_type=False), nullable=False),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_flow_state_client_id_client'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_flow_state_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flow_state')),
    sa.UniqueConstraint('client_id', 'channel', name=op.f('uq_flow_state_client_id_channel'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flow_state')
    # ### end Alembic commands ###
